site_name: Notes by Bitenergie

theme:
    name: 'material'
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

    features:
      - navigation.footer
      - navigation.instant
      - navigation.tabs

nav:
  - Home: index.md
  - Jupyter: 
    - Gallery: generated/gallery/
  - Links:
    - Links/Awesome HLK.md
    - Links/Datenbanken.md
    - Links/Dokumente.md
    - Links/Normen.md
    - Links/Vereine.md
    - Links/Zertifikate.md
  - Normen: 
    - Sia 380-1: 
      - Sia 380-1/Fenster.md
      - Sia 380-1/Grundlagen.md
      - Sia 380-1/wärmebrücken.md
    - Sia 384-7:
      - Sia 384-7/Tabelle.md
    - SIA 2024:
      - Sia2024/index.md
      - Sia2024/Dokumentation.md
      - Sia2024/Resultate.md
      - Sia2024/generated.md
    - SIA 2028:
      - sia2028/monat.md
      - sia2028/Bins.md
    - Energievollzug:
      - Energievollzug/Tabellen.md
  - Cheat Sheet:
    - cheat_sheet/heizung.md


extra_css:
  - ./stylesheets/extra.css
  
extra:
  generator: false


# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - tables
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
      toc_depth: 2
  - pymdownx.details
  - attr_list
  - md_in_html
    
plugins:
  - search
  - roamlinks 
  - mermaid2
  - gallery:
      examples_dirs: docs/examples          # path to your example scripts
      gallery_dirs: docs/generated/gallery  # where to save generated gallery
      backreferences_dir: docs/generated/backreferences  # where to generate the back references summary
      doc_module: ['mkdocs_gallery', 'numpy']
      image_scrapers: matplotlib
      within_subsection_order: FileNameSortKey

      #  org: bitenergie
      #  repo: notes
      #   branch: gh-pages  # Use a branch that hosts your docs.
      #   #binderhub_url: https://mybinder.org
      #   dependencies: docs/binder_cfg/requirements.txt  # binder configuration files
      #   # see https://mybinder.readthedocs.io/en/latest/using/config_files.html#config-files
      #   # these will be copied to the .binder/ directory of the site.

      #   #notebooks_dir: notebooks  # Notebooks for Binder will be copied to this dir (relative to built doc root).
      #   #use_jupyter_lab: True     # Binder links will start Jupyter Lab instead of the Jupyter Notebook interface.
      # # specify the order of examples to be according to filename
      show_memory: True
      matplotlib_animations: True
      image_srcset: ['2x']


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
